from django.urls import path
from . import views

urlpatterns = [
    path('index', views.index, name='index'),
    path('nosotros', views.nosotros, name='nosotros'),
    path('anunciosEs', views.anunciosEs, name='anunciosEs'),
    path('anunciosPi', views.anunciosPi, name='anunciosPi'),
    path('anunciosTej', views.anunciosTej, name='anunciosTej'),
    path('anunciosOrf', views.anunciosOrf, name='anunciosOrf'),
    path('blog', views.blog, name='blog'),
    path('base', views.base, name='base'),
    path('BlogArte', views.BlogArte, name='BlogArte'),
    path('BlogEscultura', views.BlogEscultura, name='BlogEscultura'),
    path('BlogPintura', views.BlogPintura, name='BlogPintura'),
    path('BlogTejido', views.BlogTejido, name='BlogTejido'),
    path('BlogTejido2', views.BlogTejido2, name='BlogTejido2'),
    path('BlogOrfebreria', views.BlogOrfebreria, name='BlogOrfebreria'),
    path('contacto', views.contacto, name='contacto'),
    path('EsCristo', views.EsCristo, name='EsCristo'),
    path('EsDavid', views.EsDavid, name='EsDavid'),
    path('EsEsfinge', views.EsEsfinge, name='EsEsfinge'),
    path('EsEstatua', views.EsEstatua, name='EsEstatua'),
    path('EsSirena', views.EsSirena, name='EsSirena'),
    path('EsVenus', views.EsVenus, name='EsVenus'),
    path('OrfMaikol', views.OrfMaikol, name='OrfMaikol'),
    path('OrfRam', views.OrfRam, name='OrfRam'),
    path('OrfTutanmamon', views.OrfTutanmamon, name='OrfTutanmamon'),
    path('Pimona', views.Pimona, name='Pimona'),
    path('PiNoche', views.PiNoche, name='PiNoche'),
    path('PiSwing', views.PiSwing, name='PiSwing'),
    path('TejCoral', views.TejCoral, name='TejCoral'),
    path('TejCorazon', views.TejCorazon, name='TejCorazon'),
    path('TejMuralla', views.TejMuralla, name='TejMuralla'),
    path('entrada', views.entrada, name='entrada'),
    path('listadoSQL', views.listadoSQL, name='ListadoSQL'),
    path('agregar-obra', views.agregar_obra, name='agregar_obra'),
    path('listar-obra', views.listar_obra, name='listar_obra'),
    path('modificar-obra/<id>/', views.modificar_obra, name='modificar_obra'),
    path('eliminar-obra/<id>/', views.eliminar_obra, name='eliminar_obra'),
]
