# Generated by Django 4.1.2 on 2023-07-08 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('id_artista', models.AutoField(db_column='idArtista', primary_key=True, serialize=False)),
                ('telefono', models.CharField(max_length=45)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=45)),
                ('tipo_obra', models.IntegerField(choices=[[0, 'Pintura'], [1, 'Escultura'], [2, 'Tejido'], [3, 'Orfebreria']])),
                ('avisos', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id_especialidad', models.AutoField(db_column='idEspecialidad', primary_key=True, serialize=False)),
                ('especialidad', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('nombre_obra', models.CharField(max_length=40)),
                ('precio', models.FloatField()),
                ('id_obra', models.AutoField(db_column='idObra', primary_key=True, serialize=False)),
                ('id_artista', models.ForeignKey(db_column='idArtista', on_delete=django.db.models.deletion.CASCADE, to='artistas.artista')),
                ('id_especialidad', models.ForeignKey(db_column='idEspecialidad', on_delete=django.db.models.deletion.CASCADE, to='artistas.especialidad')),
            ],
        ),
        migrations.AddField(
            model_name='artista',
            name='id_especialidad',
            field=models.ForeignKey(db_column='idEspecialidad', on_delete=django.db.models.deletion.CASCADE, to='artistas.especialidad'),
        ),
    ]
